### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by hsch0** [juchong/ADIS16228-Arduino-Teensy#1]
I imported this library to the Arduino IDE and tried to compile it for my Arduino Nano. I get a lot of errors when I try to compile the example:
```
Arduino: 1.8.5 (Linux), Board: "Arduino Nano, ATmega328P"

/tmp/arduino_modified_sketch_267649/ADIS16228_Teensy_Example.ino: In function 'void setup()':
ADIS16228_Teensy_Example:68: error: 'inputString' was not declared in this scope
     inputString.reserve(200); // Reserve 200 bytes for the inputString
     ^
/tmp/arduino_modified_sketch_267649/ADIS16228_Teensy_Example.ino: In function 'void serialEvent()':
ADIS16228_Teensy_Example:96: error: 'COMMAND' was not declared in this scope
             IMU.regWrite(COMMAND, 0x0800);
                          ^
/tmp/arduino_modified_sketch_267649/ADIS16228_Teensy_Example.ino: In function 'void loop()':
ADIS16228_Teensy_Example:113: error: 'printCounter' was not declared in this scope
     printCounter ++;
     ^
ADIS16228_Teensy_Example:117: error: 'scaleData' was not declared in this scope
         scaleData(); // Scale data acquired from the IMU
                   ^
ADIS16228_Teensy_Example:133: error: 'MSC' was not declared in this scope
         Serial.println(MSC,HEX);
                        ^
ADIS16228_Teensy_Example:135: error: 'SENS' was not declared in this scope
         Serial.println(SENS,HEX);
                        ^
ADIS16228_Teensy_Example:137: error: 'SMPL' was not declared in this scope
         Serial.println(SMPL,HEX);
                        ^
ADIS16228_Teensy_Example:143: error: 'GXS' was not declared in this scope
         Serial.println(GXS);
                        ^
ADIS16228_Teensy_Example:145: error: 'GYS' was not declared in this scope
         Serial.println(GYS);
                        ^
ADIS16228_Teensy_Example:147: error: 'GZS' was not declared in this scope
         Serial.println(GZS);
                        ^
ADIS16228_Teensy_Example:151: error: 'AXS' was not declared in this scope
         Serial.println(AXS);
                        ^
ADIS16228_Teensy_Example:153: error: 'AYS' was not declared in this scope
         Serial.println(AYS);
                        ^
ADIS16228_Teensy_Example:155: error: 'AZS' was not declared in this scope
         Serial.println(AZS);
                        ^
ADIS16228_Teensy_Example:159: error: 'MXS' was not declared in this scope
         Serial.println(MXS);
                        ^
ADIS16228_Teensy_Example:161: error: 'MYS' was not declared in this scope
         Serial.println(MYS);
                        ^
ADIS16228_Teensy_Example:163: error: 'MZS' was not declared in this scope
         Serial.println(MZS);
                        ^
ADIS16228_Teensy_Example:167: error: 'BAROS' was not declared in this scope
         Serial.println(BAROS);
                        ^
ADIS16228_Teensy_Example:178: error: 'burstData' was not declared in this scope
         Serial.println((*(burstData + 0)));
                           ^
exit status 1
'inputString' was not declared in this scope

```

**Comment by juchong** [comment]
This project was designed around an Arduino Teensy, not an Arduino Nano. Please try compiling against the Teensyduino plugin.

**Comment by omarkhan81** [comment]
I am having similar compile time errors for teensy as well. Please resolve these issues so all can benefit from your work.

**Comment by juchong** [comment]
@omarkhan81 the issue was already resolved. Please try compiling against the Teensyduino libraries.

**Comment by omarkhan81** [comment]
Hi
I have tried to compile using teensyduino. I get following errors

Arduino: 1.8.3 (Windows 10), TD: 1.41, Board: "Teensy 3.6, Serial, 180 MHz, Faster, US English"

ADIS16228_Teensy_Example: In function 'void setup()':
ADIS16228_Teensy_Example:66: error: 'inputString' was not declared in this scope
     inputString.reserve(200); // Reserve 200 bytes for the inputString

     ^

ADIS16228_Teensy_Example: In function 'void serialEvent()':
ADIS16228_Teensy_Example:94: error: 'COMMAND' was not declared in this scope
             IMU.regWrite(COMMAND, 0x0800);

                          ^

ADIS16228_Teensy_Example: In function 'void loop()':
ADIS16228_Teensy_Example:111: error: 'printCounter' was not declared in this scope
     printCounter ++;

     ^

ADIS16228_Teensy_Example:115: error: 'scaleData' was not declared in this scope
         scaleData(); // Scale data acquired from the IMU

                   ^

ADIS16228_Teensy_Example:131: error: 'MSC' was not declared in this scope
         Serial.println(MSC,HEX);

                        ^

ADIS16228_Teensy_Example:133: error: 'SENS' was not declared in this scope
         Serial.println(SENS,HEX);

                        ^

ADIS16228_Teensy_Example:135: error: 'SMPL' was not declared in this scope
         Serial.println(SMPL,HEX);

                        ^

ADIS16228_Teensy_Example:141: error: 'GXS' was not declared in this scope
         Serial.println(GXS);

                        ^

ADIS16228_Teensy_Example:143: error: 'GYS' was not declared in this scope
         Serial.println(GYS);

                        ^

ADIS16228_Teensy_Example:145: error: 'GZS' was not declared in this scope
         Serial.println(GZS);

                        ^

ADIS16228_Teensy_Example:149: error: 'AXS' was not declared in this scope
         Serial.println(AXS);

                        ^

ADIS16228_Teensy_Example:151: error: 'AYS' was not declared in this scope
         Serial.println(AYS);

                        ^

ADIS16228_Teensy_Example:153: error: 'AZS' was not declared in this scope
         Serial.println(AZS);

                        ^

ADIS16228_Teensy_Example:157: error: 'MXS' was not declared in this scope
         Serial.println(MXS);

                        ^

ADIS16228_Teensy_Example:159: error: 'MYS' was not declared in this scope
         Serial.println(MYS);

                        ^

ADIS16228_Teensy_Example:161: error: 'MZS' was not declared in this scope
         Serial.println(MZS);

                        ^

ADIS16228_Teensy_Example:165: error: 'BAROS' was not declared in this scope
         Serial.println(BAROS);

                        ^

ADIS16228_Teensy_Example:176: error: 'burstData' was not declared in this scope
         Serial.println((*(burstData + 0)));

                           ^

'inputString' was not declared in this scope


As you can see, the errors are about several variables not declared. Also i cannot find a function scaleData() in any part of the implementation, but you are calling it at line no. 115 of the example program. Also the printing portion of your code has a lot of Serial.println() regarding different registers, but these registered are never read in the code. 
I have downloaded the zip file from your github page and last commit was 2 years ago.
Please help as it is very important.

Warm regards
Omar

**Comment by juchong** [comment]
Omar,
It looks like none of the helper functions are present when compiling. I suspect it's because the library hasn't been installed correctly. Also, this code was tested using a Teensy 3.2, so it may not work correctly on a 3.6. The code compiles correctly on my end.

**Comment by omarkhan81** [comment]
If possible, can you email me a zip file of the latest code that compiles for teensy 3.2. My email id is omargiki@gmail.com. one favor please, please compile the code at your end before zipping. I only get 2 library files (1 .cpp and 1 .h) and 1 example file when i download from github, and there are no helper functions etc in any of these.

**Comment by juchong** [comment]
Sorry @omarkhan81 I can't do that. I'm using exactly the same code available in this repository on GitHub. The .cpp and .h files are all you need.

**Comment by omarkhan81** [comment]
I have found that some portions of example program available for ADIS16228 are the same you are using with ADIS16448. Please see if you can modify the example program so it works for ADIS16228. The ADIS16228 library does not have helper functions like ScaleData(), etc. Similarly the control registers you are printing do not exist in ADIS16228. But, they are available with ADIS16448.

**Comment by juchong** [comment]
Unfortunately @omarkhan81 I don't have time to make the changes you requested. As GitHub is an open source development community, I encourage you to make the necessary changes and submit a pull request to improve the current repository. It's important to remember that users contributing to open source repositories aren't doing it by force.
